/// Curated assessment reference data (field trial practice, public methodology); bundled with the app, not stored as a database table.
library;

/// Prefix for [TrialAssessments.instructionOverride] machine tags.
const String kCuratedLibraryInstructionPrefix = 'librarySourceId:';

/// Breadcrumb linking a trial assessment row to a curated library entry.
String curatedLibraryInstructionTag(String libraryEntryId) =>
    '$kCuratedLibraryInstructionPrefix$libraryEntryId';

/// Parses [curatedLibraryInstructionTag] ids from trial assessment rows.
Set<String> curatedLibraryIdsFromInstructionOverrides(
  Iterable<String?> instructionOverrides,
) {
  final result = <String>{};
  for (final io in instructionOverrides) {
    final s = io?.trim();
    if (s == null || s.isEmpty) continue;
    if (s.startsWith(kCuratedLibraryInstructionPrefix)) {
      result.add(s.substring(kCuratedLibraryInstructionPrefix.length));
    }
  }
  return result;
}

/// Short unique stored `code` for definitions created from [AssessmentLibrary] entries.
///
/// Schema limits `code` to 50 characters; this format stays well under that (typically
/// under 35) regardless of long curated [libraryEntryId] strings.
String curatedLibraryAssessmentDefinitionCode({
  required int trialId,
  required String libraryEntryId,
  required int disambiguator,
}) {
  final ts = DateTime.now().microsecondsSinceEpoch + disambiguator;
  final h = Object.hash(libraryEntryId, trialId, ts) & 0x7FFFFFFF;
  return 'LIB_${trialId}_$h';
}

class LibraryAssessment {
  const LibraryAssessment({
    required this.id,
    required this.name,
    required this.category,
    required this.unit,
    required this.scaleMin,
    required this.scaleMax,
    required this.dataType,
    required this.description,
  });

  final String id;
  final String name;
  final String category;
  final String unit;
  final double scaleMin;
  final double scaleMax;
  final String dataType;
  final String description;
}

class AssessmentLibrary {
  AssessmentLibrary._();

  /// Display order for category filter chips (matches [entries]).
  static const List<String> categoryDisplayOrder = [
    'Herbicide Efficacy',
    'Fungicide Efficacy',
    'Insecticide Efficacy',
    'Crop Safety',
    'Crop Growth',
    'Yield & Harvest',
    'Growth Regulator',
    'Seed & Establishment',
  ];

  static const List<LibraryAssessment> entries = [
    LibraryAssessment(
      id: 'herb_weed_control',
      name: '% weed control',
      category: 'Herbicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Visual estimate of overall weed control',
    ),
    LibraryAssessment(
      id: 'herb_weed_cover',
      name: '% weed cover',
      category: 'Herbicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Ground coverage by weeds',
    ),
    LibraryAssessment(
      id: 'herb_weed_density',
      name: 'Weed density',
      category: 'Herbicide Efficacy',
      unit: 'plants/m²',
      scaleMin: 0,
      scaleMax: 999,
      dataType: 'count',
      description: 'Weed count per unit area',
    ),
    LibraryAssessment(
      id: 'herb_weed_biomass',
      name: 'Weed biomass',
      category: 'Herbicide Efficacy',
      unit: 'g/m²',
      scaleMin: 0,
      scaleMax: 9999,
      dataType: 'numeric',
      description: 'Dried weed weight per area',
    ),
    LibraryAssessment(
      id: 'herb_weed_height',
      name: 'Weed height',
      category: 'Herbicide Efficacy',
      unit: 'cm',
      scaleMin: 0,
      scaleMax: 300,
      dataType: 'numeric',
      description: 'Average weed height',
    ),
    LibraryAssessment(
      id: 'herb_broadleaf_control',
      name: '% broadleaf control',
      category: 'Herbicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Control of broadleaf weeds',
    ),
    LibraryAssessment(
      id: 'herb_grass_control',
      name: '% grass control',
      category: 'Herbicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Control of grass weeds',
    ),
    LibraryAssessment(
      id: 'herb_specific_weed_control',
      name: '% specific weed control',
      category: 'Herbicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Control of named weed species',
    ),
    LibraryAssessment(
      id: 'fung_disease_severity',
      name: '% disease severity',
      category: 'Fungicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Proportion of tissue affected',
    ),
    LibraryAssessment(
      id: 'fung_disease_incidence',
      name: '% disease incidence',
      category: 'Fungicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Proportion of plants affected',
    ),
    LibraryAssessment(
      id: 'fung_infected_leaf_area',
      name: '% infected leaf area',
      category: 'Fungicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Leaf area showing symptoms',
    ),
    LibraryAssessment(
      id: 'fung_disease_rating',
      name: 'Disease rating',
      category: 'Fungicide Efficacy',
      unit: 'score',
      scaleMin: 0,
      scaleMax: 9,
      dataType: 'ordinal',
      description: 'Standard disease severity scale',
    ),
    LibraryAssessment(
      id: 'fung_disease_control',
      name: '% disease control',
      category: 'Fungicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Reduction vs untreated',
    ),
    LibraryAssessment(
      id: 'fung_lesion_count',
      name: 'Lesion count',
      category: 'Fungicide Efficacy',
      unit: 'count',
      scaleMin: 0,
      scaleMax: 999,
      dataType: 'count',
      description: 'Number of disease lesions per sample',
    ),
    LibraryAssessment(
      id: 'fung_flag_leaf_infection',
      name: '% flag leaf infection',
      category: 'Fungicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Disease on flag leaf specifically',
    ),
    LibraryAssessment(
      id: 'fung_head_blight',
      name: '% head blight',
      category: 'Fungicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Fusarium head blight severity',
    ),
    LibraryAssessment(
      id: 'fung_leaf_rust',
      name: '% leaf rust severity',
      category: 'Fungicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Rust coverage on leaf tissue',
    ),
    LibraryAssessment(
      id: 'fung_mildew',
      name: '% mildew severity',
      category: 'Fungicide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Powdery or downy mildew coverage',
    ),
    LibraryAssessment(
      id: 'insec_insect_count',
      name: 'Insect count',
      category: 'Insecticide Efficacy',
      unit: 'count',
      scaleMin: 0,
      scaleMax: 999,
      dataType: 'count',
      description: 'Insects per sample unit',
    ),
    LibraryAssessment(
      id: 'insec_insect_damage',
      name: '% insect damage',
      category: 'Insecticide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Tissue damaged by insects',
    ),
    LibraryAssessment(
      id: 'insec_insect_rating',
      name: 'Insect rating',
      category: 'Insecticide Efficacy',
      unit: 'score',
      scaleMin: 0,
      scaleMax: 9,
      dataType: 'ordinal',
      description: 'Standardized pest pressure scale',
    ),
    LibraryAssessment(
      id: 'insec_larvae_count',
      name: 'Larvae count',
      category: 'Insecticide Efficacy',
      unit: 'count',
      scaleMin: 0,
      scaleMax: 999,
      dataType: 'count',
      description: 'Larvae per sample',
    ),
    LibraryAssessment(
      id: 'insec_pest_control',
      name: '% pest control',
      category: 'Insecticide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Reduction vs untreated',
    ),
    LibraryAssessment(
      id: 'insec_aphid_count',
      name: 'Aphid count',
      category: 'Insecticide Efficacy',
      unit: 'count',
      scaleMin: 0,
      scaleMax: 999,
      dataType: 'count',
      description: 'Aphids per plant, leaf, or tiller',
    ),
    LibraryAssessment(
      id: 'insec_defoliation',
      name: '% defoliation',
      category: 'Insecticide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Leaf area consumed by insects',
    ),
    LibraryAssessment(
      id: 'insec_exit_holes',
      name: 'Exit hole count',
      category: 'Insecticide Efficacy',
      unit: 'count',
      scaleMin: 0,
      scaleMax: 99,
      dataType: 'count',
      description: 'Borer exit holes per unit',
    ),
    LibraryAssessment(
      id: 'insec_eggs',
      name: 'Eggs per plant',
      category: 'Insecticide Efficacy',
      unit: 'count',
      scaleMin: 0,
      scaleMax: 999,
      dataType: 'count',
      description: 'Insect eggs per plant',
    ),
    LibraryAssessment(
      id: 'insec_fruit_damage',
      name: '% fruit damage',
      category: 'Insecticide Efficacy',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Proportion of fruit damaged by insects',
    ),
    LibraryAssessment(
      id: 'phyto_phytotoxicity',
      name: '% phytotoxicity',
      category: 'Crop Safety',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Crop injury from treatment application',
    ),
    LibraryAssessment(
      id: 'phyto_rating',
      name: 'Phytotoxicity rating',
      category: 'Crop Safety',
      unit: 'score',
      scaleMin: 0,
      scaleMax: 9,
      dataType: 'ordinal',
      description: 'EWRS or national phytotoxicity scale',
    ),
    LibraryAssessment(
      id: 'phyto_crop_injury',
      name: '% crop injury',
      category: 'Crop Safety',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Visible crop damage from any source',
    ),
    LibraryAssessment(
      id: 'phyto_chlorosis',
      name: '% chlorosis',
      category: 'Crop Safety',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Yellowing of plant tissue',
    ),
    LibraryAssessment(
      id: 'phyto_necrosis',
      name: '% necrosis',
      category: 'Crop Safety',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Dead tissue from treatment injury',
    ),
    LibraryAssessment(
      id: 'phyto_stunting',
      name: '% stunting',
      category: 'Crop Safety',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Growth reduction vs untreated',
    ),
    LibraryAssessment(
      id: 'phyto_vigor',
      name: 'Crop vigor',
      category: 'Crop Safety',
      unit: 'score',
      scaleMin: 1,
      scaleMax: 9,
      dataType: 'ordinal',
      description: 'Overall plant health and growth rating',
    ),
    LibraryAssessment(
      id: 'phyto_stand_reduction',
      name: '% stand reduction',
      category: 'Crop Safety',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Plant loss from treatment application',
    ),
    LibraryAssessment(
      id: 'growth_plant_height',
      name: 'Plant height',
      category: 'Crop Growth',
      unit: 'cm',
      scaleMin: 0,
      scaleMax: 500,
      dataType: 'numeric',
      description: 'Ground to top of canopy',
    ),
    LibraryAssessment(
      id: 'growth_stem_diameter',
      name: 'Stem diameter',
      category: 'Crop Growth',
      unit: 'mm',
      scaleMin: 0,
      scaleMax: 99,
      dataType: 'numeric',
      description: 'Main stem diameter at base',
    ),
    LibraryAssessment(
      id: 'growth_stand_count',
      name: 'Stand count',
      category: 'Crop Growth',
      unit: 'count',
      scaleMin: 0,
      scaleMax: 999,
      dataType: 'count',
      description: 'Plants per unit area',
    ),
    LibraryAssessment(
      id: 'growth_emergence',
      name: '% emergence',
      category: 'Crop Growth',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Emerged plants vs planted',
    ),
    LibraryAssessment(
      id: 'growth_days_emergence',
      name: 'Days to emergence',
      category: 'Crop Growth',
      unit: 'days',
      scaleMin: 0,
      scaleMax: 60,
      dataType: 'count',
      description: 'Planting to 50% emergence',
    ),
    LibraryAssessment(
      id: 'growth_days_flowering',
      name: 'Days to flowering',
      category: 'Crop Growth',
      unit: 'days',
      scaleMin: 0,
      scaleMax: 200,
      dataType: 'count',
      description: 'Planting to 50% flowering',
    ),
    LibraryAssessment(
      id: 'growth_days_maturity',
      name: 'Days to maturity',
      category: 'Crop Growth',
      unit: 'days',
      scaleMin: 0,
      scaleMax: 365,
      dataType: 'count',
      description: 'Planting to physiological maturity',
    ),
    LibraryAssessment(
      id: 'growth_tiller_count',
      name: 'Tiller count',
      category: 'Crop Growth',
      unit: 'count',
      scaleMin: 0,
      scaleMax: 99,
      dataType: 'count',
      description: 'Tillers per plant',
    ),
    LibraryAssessment(
      id: 'growth_node_count',
      name: 'Nodes per plant',
      category: 'Crop Growth',
      unit: 'count',
      scaleMin: 0,
      scaleMax: 30,
      dataType: 'count',
      description: 'Node count at staging',
    ),
    LibraryAssessment(
      id: 'growth_bbch',
      name: 'BBCH growth stage',
      category: 'Crop Growth',
      unit: 'stage',
      scaleMin: 0,
      scaleMax: 99,
      dataType: 'ordinal',
      description: 'BBCH decimal growth stage code',
    ),
    LibraryAssessment(
      id: 'growth_canopy_closure',
      name: 'Canopy closure',
      category: 'Crop Growth',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Ground covered by crop canopy',
    ),
    LibraryAssessment(
      id: 'growth_root_rating',
      name: 'Root rating',
      category: 'Crop Growth',
      unit: 'score',
      scaleMin: 1,
      scaleMax: 9,
      dataType: 'ordinal',
      description: 'Root health and mass assessment',
    ),
    LibraryAssessment(
      id: 'growth_lodging',
      name: '% lodging',
      category: 'Crop Growth',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Percent of plot lodged',
    ),
    LibraryAssessment(
      id: 'growth_lodging_severity',
      name: 'Lodging severity',
      category: 'Crop Growth',
      unit: 'score',
      scaleMin: 0,
      scaleMax: 9,
      dataType: 'ordinal',
      description: 'Degree of lodging on ordinal scale',
    ),
    LibraryAssessment(
      id: 'growth_green_stem_count',
      name: 'Green stem count',
      category: 'Crop Growth',
      unit: 'count',
      scaleMin: 0,
      scaleMax: 999,
      dataType: 'count',
      description: 'Living stems per area',
    ),
    LibraryAssessment(
      id: 'yield_grain_kg',
      name: 'Grain yield',
      category: 'Yield & Harvest',
      unit: 'kg/plot',
      scaleMin: 0,
      scaleMax: 99999,
      dataType: 'numeric',
      description: 'Harvested grain weight per plot',
    ),
    LibraryAssessment(
      id: 'yield_bu_acre',
      name: 'Yield (bu/acre)',
      category: 'Yield & Harvest',
      unit: 'bu/acre',
      scaleMin: 0,
      scaleMax: 500,
      dataType: 'numeric',
      description: 'Converted yield in bushels per acre',
    ),
    LibraryAssessment(
      id: 'yield_t_ha',
      name: 'Yield (t/ha)',
      category: 'Yield & Harvest',
      unit: 't/ha',
      scaleMin: 0,
      scaleMax: 30,
      dataType: 'numeric',
      description: 'Converted yield in tonnes per hectare',
    ),
    LibraryAssessment(
      id: 'yield_moisture',
      name: 'Moisture at harvest',
      category: 'Yield & Harvest',
      unit: '%',
      scaleMin: 0,
      scaleMax: 50,
      dataType: 'numeric',
      description: 'Grain moisture content at harvest',
    ),
    LibraryAssessment(
      id: 'yield_test_weight',
      name: 'Test weight',
      category: 'Yield & Harvest',
      unit: 'kg/hL',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Bulk density of harvested grain',
    ),
    LibraryAssessment(
      id: 'yield_tkw',
      name: '1000 kernel weight',
      category: 'Yield & Harvest',
      unit: 'g',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Weight of 1000 seeds as size indicator',
    ),
    LibraryAssessment(
      id: 'yield_biomass',
      name: 'Biomass yield',
      category: 'Yield & Harvest',
      unit: 'g/plot',
      scaleMin: 0,
      scaleMax: 99999,
      dataType: 'numeric',
      description: 'Total above-ground biomass per plot',
    ),
    LibraryAssessment(
      id: 'yield_fruit_count',
      name: 'Fruit count',
      category: 'Yield & Harvest',
      unit: 'count',
      scaleMin: 0,
      scaleMax: 999,
      dataType: 'count',
      description: 'Harvestable fruits per plant or plot',
    ),
    LibraryAssessment(
      id: 'yield_fruit_weight',
      name: 'Fruit weight',
      category: 'Yield & Harvest',
      unit: 'g',
      scaleMin: 0,
      scaleMax: 9999,
      dataType: 'numeric',
      description: 'Weight per fruit or per sample',
    ),
    LibraryAssessment(
      id: 'yield_marketable',
      name: '% marketable yield',
      category: 'Yield & Harvest',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Proportion of harvest meeting quality grade',
    ),
    LibraryAssessment(
      id: 'yield_harvest_index',
      name: 'Harvest index',
      category: 'Yield & Harvest',
      unit: 'ratio',
      scaleMin: 0,
      scaleMax: 1,
      dataType: 'numeric',
      description: 'Grain weight divided by total biomass',
    ),
    LibraryAssessment(
      id: 'pgr_height_reduction',
      name: '% height reduction',
      category: 'Growth Regulator',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Height reduction vs untreated control',
    ),
    LibraryAssessment(
      id: 'pgr_internode_length',
      name: 'Internode length',
      category: 'Growth Regulator',
      unit: 'cm',
      scaleMin: 0,
      scaleMax: 50,
      dataType: 'numeric',
      description: 'Specific internode measurement',
    ),
    LibraryAssessment(
      id: 'pgr_lodging_reduction',
      name: '% lodging reduction',
      category: 'Growth Regulator',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Lodging improvement vs untreated',
    ),
    LibraryAssessment(
      id: 'pgr_stem_strength',
      name: 'Stem strength',
      category: 'Growth Regulator',
      unit: 'score',
      scaleMin: 1,
      scaleMax: 9,
      dataType: 'ordinal',
      description: 'Resistance to push test',
    ),
    LibraryAssessment(
      id: 'seed_germination',
      name: '% germination',
      category: 'Seed & Establishment',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Lab or field germination rate',
    ),
    LibraryAssessment(
      id: 'seed_vigor',
      name: 'Seedling vigor',
      category: 'Seed & Establishment',
      unit: 'score',
      scaleMin: 1,
      scaleMax: 9,
      dataType: 'ordinal',
      description: 'Early seedling health rating',
    ),
    LibraryAssessment(
      id: 'seed_survival',
      name: '% seedling survival',
      category: 'Seed & Establishment',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Survival to target growth stage',
    ),
    LibraryAssessment(
      id: 'seed_damping_off',
      name: '% damping off',
      category: 'Seed & Establishment',
      unit: '%',
      scaleMin: 0,
      scaleMax: 100,
      dataType: 'numeric',
      description: 'Seedling disease incidence',
    ),
    LibraryAssessment(
      id: 'seed_root_length',
      name: 'Root length',
      category: 'Seed & Establishment',
      unit: 'cm',
      scaleMin: 0,
      scaleMax: 50,
      dataType: 'numeric',
      description: 'Seedling root length',
    ),
    LibraryAssessment(
      id: 'seed_shoot_length',
      name: 'Shoot length',
      category: 'Seed & Establishment',
      unit: 'cm',
      scaleMin: 0,
      scaleMax: 50,
      dataType: 'numeric',
      description: 'Seedling shoot length',
    ),
    LibraryAssessment(
      id: 'seed_weight_per_plot',
      name: 'Seed weight per plot',
      category: 'Seed & Establishment',
      unit: 'g',
      scaleMin: 0,
      scaleMax: 9999,
      dataType: 'numeric',
      description: 'Seed lot weight per plot',
    ),
  ];

  /// Category names in stable display order.
  static List<String> get categories => categoryDisplayOrder;

  static List<LibraryAssessment> byCategory(String category) =>
      entries.where((e) => e.category == category).toList();

  static List<LibraryAssessment> search(String query) {
    final q = query.toLowerCase().trim();
    if (q.isEmpty) return List<LibraryAssessment>.from(entries);
    return entries
        .where(
          (e) =>
              e.name.toLowerCase().contains(q) ||
              e.description.toLowerCase().contains(q) ||
              e.category.toLowerCase().contains(q),
        )
        .toList();
  }

  static LibraryAssessment? byId(String id) {
    for (final e in entries) {
      if (e.id == id) return e;
    }
    return null;
  }
}
